export const ATTR = "data-pm-carousel"
export const ATTRPAGING = `${ATTR}-paging`
export const ATTRWRAPPER = `${ATTR}-wrapper`
export const ATTROVERFLOW = `${ATTR}-overflow`
export const ATTRITEM = `${ATTR}-item`
export const ATTRPREV = `${ATTR}-prev`
export const ATTRNEXT = `${ATTR}-next`
export const ATTRPLAYSTOP = `${ATTR}-playstop`
export const TRANSITION = "transform .5s ease-in-out"
export const TRANSITION_SWIPE = "transform .1s ease-out"
export const ACTIVECLASS = "is-active"
export const SLIDE_MIN_RATIO = 6
